/**
 * SpineMetrics API Layer v2
 * ─────────────────────────────────────────────────────────────────────────────
 * The LLM is used ONLY to optionally enhance the prose of a fully deterministic
 * report already generated by clinicalEngine.js.
 *
 * If the API call fails for any reason, the deterministic report is returned
 * unchanged. The tool always works without LLM connectivity.
 */

// ─── System prompt for LLM prose enhancement ─────────────────────────────────
const ENHANCEMENT_SYSTEM_PROMPT = `You are the SpineMetrics clinical report editor.

You will receive a fully structured clinical report that was generated by a deterministic rule-based engine using validated published cutoffs. Your ONLY job is to:

1. Improve the prose flow and clinical readability.
2. Add clinical context where it is genuinely relevant and evidence-based.
3. Review any uploaded imaging for gross quality, positioning, and anatomical completeness — comment briefly.

ABSOLUTE RULES — do not violate:
- Do NOT change any numeric values, cutoffs, or classifications already in the report.
- Do NOT add references that are not already present or are not real published studies.
- Do NOT use "sarcopenia" as a diagnosis from imaging alone. The phrase "low muscle mass (radiographic proxy)" is correct and must be preserved.
- Do NOT add any treatment recommendations.
- Do NOT remove any limitation statements or the mandatory disclaimer.
- Do NOT alter the section structure (h2/h3 headings must remain).
- If you cannot improve the report, return it unchanged.
- Keep the report concise. Do not pad with filler sentences.

The report is already clinically correct. You are only polishing prose and adding imaging assessment if an image was provided.`

// ─── API URL ──────────────────────────────────────────────────────────────────
const getApiUrl = () => {
  if (typeof import.meta !== 'undefined' && import.meta.env) {
    if (import.meta.env.VITE_API_URL) return import.meta.env.VITE_API_URL
    if (import.meta.env.DEV) return 'https://api.anthropic.com/v1/messages'
  }
  return '/api/analyze'
}

// ─── LLM Enhancement (optional) ──────────────────────────────────────────────
/**
 * Attempts to enhance the deterministic report using the LLM.
 * Returns the original report if the API call fails or times out.
 *
 * @param {string} deterministicReport - Already-generated full report text
 * @param {string|null} imageBase64 - Optional base64 image for visual assessment
 * @param {string|null} imageMime - Image MIME type
 * @returns {Promise<string>} Enhanced or original report
 */
export async function enhanceReportWithLLM(deterministicReport, imageBase64, imageMime) {
  const content = []

  if (imageBase64 && imageMime) {
    content.push({
      type: 'image',
      source: { type: 'base64', media_type: imageMime, data: imageBase64 },
    })
    content.push({
      type: 'text',
      text: 'The image above was uploaded by the clinician for documentation purposes. Comment briefly in the "Imaging Assessment" section on: (1) whether the correct anatomical level and view appear to be captured, (2) gross image quality and any obvious artifacts, (3) positioning concerns. Do not claim to perform automated measurement. Then enhance the full report below.',
    })
  }

  content.push({
    type: 'text',
    text: `Here is the deterministic clinical report to enhance:\n\n${deterministicReport}`,
  })

  const payload = {
    model: 'claude-sonnet-4-20250514',
    max_tokens: 1000,
    system: ENHANCEMENT_SYSTEM_PROMPT,
    messages: [{ role: 'user', content }],
  }

  const headers = { 'Content-Type': 'application/json' }

  const isDev =
    typeof import.meta !== 'undefined' &&
    import.meta.env?.DEV

  if (isDev && import.meta.env.VITE_ANTHROPIC_API_KEY) {
    headers['x-api-key'] = import.meta.env.VITE_ANTHROPIC_API_KEY
    headers['anthropic-version'] = '2023-06-01'
  }

  // 20-second timeout — if the API is slow, return the deterministic report
  const controller = new AbortController()
  const timeout = setTimeout(() => controller.abort(), 20000)

  try {
    const res = await fetch(getApiUrl(), {
      method: 'POST',
      headers,
      body: JSON.stringify(payload),
      signal: controller.signal,
    })
    clearTimeout(timeout)

    const data = await res.json()
    if (data.error) throw new Error(data.error.message)

    const enhanced = data.content?.map(b => b.text || '').join('\n') || ''
    return enhanced.trim() || deterministicReport
  } catch (err) {
    clearTimeout(timeout)
    // Return deterministic report unchanged — app still functions fully
    console.warn('SpineMetrics: LLM enhancement unavailable —', err.message)
    return deterministicReport
  }
}
