import { useState, useRef, useCallback } from 'react'
import './index.css'
import { MODULES, FIELDS } from './constants.js'
import { runSpineMetrics, buildPrompt, computeDerived } from './api.js'
import { renderMarkdown } from './markdown.js'

// ─── Upload Zone Component ────────────────────────────────────────────────────
function UploadZone({ image, imageName, onFile, onClear }) {
  const [drag, setDrag] = useState(false)

  const handleDrop = useCallback((e) => {
    e.preventDefault()
    setDrag(false)
    const file = e.dataTransfer.files[0]
    if (file) onFile(file)
  }, [onFile])

  return (
    <div
      className={`upload-zone${drag ? ' drag' : ''}`}
      onDragOver={e => { e.preventDefault(); setDrag(true) }}
      onDragLeave={() => setDrag(false)}
      onDrop={handleDrop}
    >
      <input
        type="file"
        accept="image/jpeg,image/png,image/webp,image/gif"
        onChange={e => e.target.files[0] && onFile(e.target.files[0])}
      />
      {!image ? (
        <>
          <div className="upload-icon">📂</div>
          <div className="upload-text">Drop image or click to browse</div>
          <div className="upload-sub">JPEG · PNG · WEBP · DICOM export as image</div>
        </>
      ) : (
        <div className="upload-preview">
          <button
            className="upload-clear"
            onClick={e => { e.stopPropagation(); onClear() }}
            title="Remove image"
          >✕</button>
          <img src={image} alt="Uploaded clinical imaging" />
          <div className="upload-file-name">✓ {imageName} — will be analyzed</div>
        </div>
      )}
    </div>
  )
}

// ─── Field Component ──────────────────────────────────────────────────────────
function FormField({ field, value, onChange }) {
  return (
    <div className={`field${field.type === 'text' ? ' field-full' : ''}`}>
      <label>
        {field.label}
        {field.required && <span className="req-star">*</span>}
      </label>
      {field.type === 'select' ? (
        <select value={value || ''} onChange={e => onChange(field.id, e.target.value)}>
          <option value="">— select —</option>
          {field.options.map(o => <option key={o} value={o}>{o}</option>)}
        </select>
      ) : (
        <input
          type={field.type === 'text' ? 'text' : 'number'}
          step="any"
          placeholder={field.placeholder}
          value={value || ''}
          onChange={e => onChange(field.id, e.target.value)}
        />
      )}
    </div>
  )
}

// ─── Warning Box ──────────────────────────────────────────────────────────────
function WarningBox({ warnings }) {
  if (!warnings.length) return null
  return (
    <>
      {warnings.map((w, i) => (
        <div className="warning-box" key={i}>
          <span className="warning-box-label">⚠ Clinical Flag</span>
          {w}
        </div>
      ))}
    </>
  )
}

// ─── Pre-computed Values Banner ───────────────────────────────────────────────
function PrecomputedBanner({ module, values, accentColor }) {
  const derived = computeDerived(module, values)
  if (!derived.length) return null

  return (
    <div className="precomputed">
      <span className="precomputed-label" style={{ color: accentColor }}>
        Pre-computed ·
      </span>
      {derived.map((d, i) => (
        <span className="precomputed-value" key={i}>{d}</span>
      ))}
    </div>
  )
}

// ─── Report Component ─────────────────────────────────────────────────────────
function Report({ report, moduleName, moduleColor }) {
  const copyReport = () => navigator.clipboard.writeText(report)
  const printReport = () => window.print()

  return (
    <div className="report">
      <div className="report-header">
        <div>
          <div className="report-title">Clinical Measurement Report</div>
        </div>
        <div className="report-meta">
          <span
            className="report-module"
            style={{ background: moduleColor }}
          >
            {moduleName}
          </span>
          <span className="report-ts">{new Date().toLocaleString()}</span>
        </div>
      </div>

      <div
        className="report-body"
        dangerouslySetInnerHTML={{ __html: renderMarkdown(report) }}
      />

      <div className="disclaimer-box">
        <span className="disclaimer-label">⚠ Mandatory Disclaimer</span>
        This report is generated by SpineMetrics (v1.0) for research and clinical decision-support purposes only.
        It does not constitute a medical diagnosis or treatment recommendation. All outputs must be reviewed
        and validated by a licensed physician or qualified healthcare professional before clinical use.
        CT-based muscle measurements are imaging proxies only — sarcopenia diagnosis requires assessment of
        muscle strength and/or physical performance per EWGSOP2 (Cruz-Jentoft AJ et al., Age Ageing,
        2019;48:16–31). This tool is not FDA-cleared and is not a regulated medical device.
      </div>

      <div className="report-actions">
        <button className="btn-outline" onClick={copyReport}>Copy Report</button>
        <button className="btn-outline" onClick={printReport}>Print / Save PDF</button>
      </div>
    </div>
  )
}

// ─── Main App ─────────────────────────────────────────────────────────────────
export default function App() {
  const [selectedModule, setSelectedModule] = useState(null)
  const [values, setValues] = useState({})
  const [image, setImage] = useState(null)
  const [imageName, setImageName] = useState(null)
  const [imageBase64, setImageBase64] = useState(null)
  const [imageMime, setImageMime] = useState(null)
  const [loading, setLoading] = useState(false)
  const [report, setReport] = useState(null)
  const [error, setError] = useState(null)

  const reportRef = useRef(null)

  // ── Module selection ──
  const handleModuleSelect = (id) => {
    setSelectedModule(id)
    setValues({})
    setReport(null)
    setError(null)
    clearImage()
  }

  // ── Field change ──
  const handleField = (id, val) => setValues(v => ({ ...v, [id]: val }))

  // ── Image handling ──
  const handleFile = useCallback((file) => {
    const allowed = ['image/jpeg', 'image/png', 'image/webp', 'image/gif']
    if (!allowed.includes(file.type)) {
      setError('Unsupported file type. Please upload JPEG, PNG, or WEBP.')
      return
    }
    setError(null)
    setImage(URL.createObjectURL(file))
    setImageName(file.name)
    setImageMime(file.type)
    const reader = new FileReader()
    reader.onload = e => setImageBase64(e.target.result.split(',')[1])
    reader.readAsDataURL(file)
  }, [])

  const clearImage = () => {
    setImage(null)
    setImageName(null)
    setImageBase64(null)
    setImageMime(null)
  }

  // ── Clinical warnings ──
  const getWarnings = () => {
    const w = []
    if (!selectedModule) return w

    if (['lumbar', 'pelvic'].includes(selectedModule) &&
        values.film_type && values.film_type !== 'Standing') {
      w.push(`Non-standing film detected (${values.film_type}). Pelvic parameters (PI, PT, SS) and sagittal alignment values are unreliable on non-weight-bearing imaging. Results will be prominently flagged in the report.`)
    }

    if (selectedModule === 'pelvic' && values.pi && values.pt && values.ss) {
      const diff = Math.abs(parseFloat(values.pi) - parseFloat(values.pt) - parseFloat(values.ss))
      if (diff > 4) {
        w.push(`Geometric inconsistency: PI (${values.pi}°) ≠ PT (${values.pt}°) + SS (${values.ss}°). Difference = ${diff.toFixed(1)}°. Verify all three measurements before submitting.`)
      }
    }

    if (selectedModule === 'muscle' && !imageBase64) {
      w.push('No imaging uploaded. Values must be derived from a validated axial CT at L3 with bilateral transverse processes visible. Confirm measurements were obtained from appropriate imaging before submitting.')
    }

    if (selectedModule === 'muscle' && values.mean_hu && !imageBase64) {
      w.push('HU-based myosteatosis assessment requires DICOM-sourced imaging with scanner calibration. Values entered manually without uploaded imaging will be flagged as unverified in the report.')
    }

    if (selectedModule === 'cervical' &&
        values.film_position && values.film_position !== 'Neutral') {
      w.push(`Non-neutral neck position (${values.film_position}). Cervical alignment values in flexion/extension reflect dynamic positioning, not neutral anatomical lordosis. Clinical interpretation differs from neutral measurements.`)
    }

    return w
  }

  // ── Required fields validation ──
  const requiredMet = () => {
    if (!selectedModule) return false
    return FIELDS[selectedModule]
      .filter(f => f.required)
      .every(f => values[f.id] && values[f.id] !== '')
  }

  // ── Submit ──
  const handleSubmit = async () => {
    setLoading(true)
    setReport(null)
    setError(null)

    try {
      const precomputed = computeDerived(selectedModule, values)
      const promptText = buildPrompt({
        module: selectedModule,
        values,
        precomputed,
      })

      const result = await runSpineMetrics({
        promptText,
        imageBase64,
        imageMime,
      })

      setReport(result)
      setTimeout(() => {
        reportRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })
      }, 150)
    } catch (e) {
      setError('API error: ' + e.message + '. Check your network connection and try again.')
    } finally {
      setLoading(false)
    }
  }

  // ── Clear form ──
  const handleClear = () => {
    setValues({})
    setReport(null)
    setError(null)
    clearImage()
  }

  const currentModule = MODULES.find(m => m.id === selectedModule)
  const warnings = getWarnings()

  return (
    <div className="app">
      {/* ── Header ── */}
      <header className="header">
        <div className="header-left">
          <div className="header-logo">
            <div className="logo-mark">S</div>
            <div>
              <div className="header-title">Spine<span>Metrics</span></div>
            </div>
          </div>
          <div className="header-sub">
            Imaging-Based Clinical Decision Support · Spine &amp; Musculoskeletal Medicine
          </div>
        </div>
        <div className="header-right">
          <span className="badge-ruo">Research Use Only</span>
          <span className="badge-version">v1.0 · Not FDA-Cleared</span>
        </div>
      </header>

      {/* ── Module Selector ── */}
      <div className="section-label">Select measurement module</div>
      <div className="modules">
        {MODULES.map(m => (
          <button
            key={m.id}
            className={`module-btn${selectedModule === m.id ? ' active' : ''}`}
            onClick={() => handleModuleSelect(m.id)}
          >
            <div className="module-icon" style={{ background: m.color }}>
              {m.icon}
            </div>
            <div>
              <div className="module-name">{m.label}</div>
              <div className="module-desc">{m.desc}</div>
            </div>
          </button>
        ))}
      </div>

      {/* ── Module Content ── */}
      {selectedModule && (
        <>
          {/* Image requirement notice */}
          <div className="image-req">
            <div className="image-req-label">Required imaging</div>
            {currentModule?.imageReq}
          </div>

          {/* Upload */}
          <div className="upload-section">
            <div className="section-label">
              Upload imaging — optional (DICOM export as JPEG/PNG)
            </div>
            <UploadZone
              image={image}
              imageName={imageName}
              onFile={handleFile}
              onClear={clearImage}
            />
          </div>

          {/* Warnings */}
          <WarningBox warnings={warnings} />

          {/* Measurement fields */}
          <div className="form-section">
            <div className="section-label" style={{ marginBottom: '1rem' }}>
              Measurements — {currentModule?.label}
            </div>
            <div className="form-grid">
              {FIELDS[selectedModule].map(field => (
                <FormField
                  key={field.id}
                  field={field}
                  value={values[field.id]}
                  onChange={handleField}
                />
              ))}
            </div>
          </div>

          {/* Pre-computed preview */}
          <PrecomputedBanner
            module={selectedModule}
            values={values}
            accentColor={currentModule?.color}
          />

          {/* Submit row */}
          <div className="submit-row">
            <button
              className="btn-primary"
              disabled={!requiredMet() || loading}
              onClick={handleSubmit}
            >
              {loading ? 'Analyzing…' : 'Generate Clinical Report →'}
            </button>
            <button className="btn-secondary" onClick={handleClear}>
              Clear
            </button>
            {!requiredMet() && (
              <span className="submit-hint">
                Fill all required fields (*) to proceed
              </span>
            )}
          </div>

          {/* Loading state */}
          {loading && (
            <div className="thinking">
              <div className="thinking-dots">
                <div className="thinking-dot" />
                <div className="thinking-dot" />
                <div className="thinking-dot" />
              </div>
              <div className="thinking-label">
                SpineMetrics engine analyzing — applying validated clinical cutoffs…
              </div>
            </div>
          )}

          {/* Error */}
          {error && (
            <div className="error-box">{error}</div>
          )}

          {/* Report */}
          {report && (
            <div ref={reportRef}>
              <Report
                report={report}
                moduleName={currentModule?.label}
                moduleColor={currentModule?.color}
              />
            </div>
          )}
        </>
      )}

      {/* ── Footer ── */}
      <footer className="footer">
        <span>SpineMetrics v1.0 — Ascension Texas Spine &amp; Scoliosis</span>
        <span>
          Cutoffs: EWGSOP2 · Prado 2008 · Derstine 2018 · Martin 2013 · Schwab 2012 · Frobin 1997
        </span>
        <span>Not FDA-cleared · Not a diagnostic device · Research use only</span>
      </footer>
    </div>
  )
}
