// ─── Clinical Modules ─────────────────────────────────────────────────────────
export const MODULES = [
  {
    id: 'muscle',
    label: 'Muscle / Body Composition',
    icon: 'M',
    color: '#0E6E55',
    desc: 'L3 axial CT · Psoas CSA · SMI · Myosteatosis',
    imageReq: 'Axial CT at L3 level with bilateral transverse processes visible. Window: soft tissue (W:400, L:50). DICOM preferred.',
  },
  {
    id: 'lumbar',
    label: 'Lumbar Alignment',
    icon: 'L',
    color: '#185FA5',
    desc: 'Standing lateral XR · LL · PI · PT · PI-LL mismatch',
    imageReq: 'Weight-bearing lateral lumbar radiograph. L1 through S1 (including superior S1 endplate) must be fully visible.',
  },
  {
    id: 'cervical',
    label: 'Cervical Alignment',
    icon: 'C',
    color: '#7B3F9E',
    desc: 'Lateral XR or mid-sagittal MRI · C2–C7 Cobb',
    imageReq: 'Lateral cervical radiograph or mid-sagittal T2 MRI. C2 and C7 inferior endplates must be visible.',
  },
  {
    id: 'pelvic',
    label: 'Pelvic Parameters',
    icon: 'P',
    color: '#A0420D',
    desc: 'Standing lumbopelvic XR · PI · PT · SS',
    imageReq: 'Standing lateral lumbopelvic radiograph. Both femoral heads and entire sacrum must be visible.',
  },
]

// ─── Form Fields Per Module ───────────────────────────────────────────────────
export const FIELDS = {
  muscle: [
    { id: 'sex', label: 'Biological sex', type: 'select', options: ['Male', 'Female'], required: true },
    { id: 'height', label: 'Height (cm)', type: 'number', placeholder: 'e.g. 172', required: true },
    { id: 'weight', label: 'Weight (kg)', type: 'number', placeholder: 'e.g. 78', required: false },
    { id: 'age', label: 'Age (years)', type: 'number', placeholder: 'e.g. 65', required: false },
    { id: 'psoas_l', label: 'Left psoas CSA (cm²)', type: 'number', placeholder: 'e.g. 14.2', required: true },
    { id: 'psoas_r', label: 'Right psoas CSA (cm²)', type: 'number', placeholder: 'e.g. 13.8', required: true },
    { id: 'total_sma', label: 'Total skeletal muscle area at L3 (cm²)', type: 'number', placeholder: 'e.g. 148.4', required: true },
    { id: 'mean_hu', label: 'Mean muscle attenuation — HU (optional, DICOM only)', type: 'number', placeholder: 'e.g. 42', required: false },
    { id: 'imaging_notes', label: 'Imaging notes / contrast phase', type: 'text', placeholder: 'e.g. non-contrast, portal venous phase', required: false },
    { id: 'clinical_context', label: 'Clinical context (optional)', type: 'text', placeholder: 'e.g. pre-op lumbar fusion, cancer screening', required: false },
  ],
  lumbar: [
    { id: 'sex', label: 'Biological sex', type: 'select', options: ['Male', 'Female'], required: true },
    { id: 'age', label: 'Age (years)', type: 'number', placeholder: 'e.g. 58', required: true },
    { id: 'film_type', label: 'Film position', type: 'select', options: ['Standing', 'Supine', 'Prone', 'Unknown'], required: true },
    { id: 'll_cobb', label: 'Lumbar lordosis L1–S1 Cobb (°)', type: 'number', placeholder: 'e.g. 47', required: true },
    { id: 'pi', label: 'Pelvic incidence — PI (°)', type: 'number', placeholder: 'e.g. 54', required: true },
    { id: 'pt', label: 'Pelvic tilt — PT (°)', type: 'number', placeholder: 'e.g. 18', required: true },
    { id: 'ss', label: 'Sacral slope — SS (°)', type: 'number', placeholder: 'e.g. 36', required: false },
    { id: 'sva', label: 'Sagittal vertical axis — SVA (mm)', type: 'number', placeholder: 'e.g. 32', required: false },
    { id: 'spondylo_pct', label: 'Spondylolisthesis slip % (0 if none)', type: 'number', placeholder: 'e.g. 0', required: false },
    { id: 'disc_level', label: 'Disc height index level', type: 'select', options: ['L1-L2','L2-L3','L3-L4','L4-L5','L5-S1','Not measured'], required: false },
    { id: 'disc_height', label: 'Disc height index — DHI (0–1)', type: 'number', placeholder: 'e.g. 0.28', required: false },
    { id: 'clinical_context', label: 'Clinical context (optional)', type: 'text', placeholder: 'e.g. adult flatback deformity, revision fusion', required: false },
  ],
  cervical: [
    { id: 'sex', label: 'Biological sex', type: 'select', options: ['Male', 'Female'], required: true },
    { id: 'age', label: 'Age (years)', type: 'number', placeholder: 'e.g. 52', required: true },
    { id: 'modality', label: 'Imaging modality', type: 'select', options: ['Lateral radiograph', 'Mid-sagittal T2 MRI', 'CT sagittal reformat'], required: true },
    { id: 'film_position', label: 'Neck position', type: 'select', options: ['Neutral', 'Flexion', 'Extension', 'Unknown'], required: true },
    { id: 'method', label: 'Measurement method', type: 'select', options: ['Cobb (standard)', 'Harrison posterior tangent', 'Unknown'], required: true },
    { id: 'c2c7_cobb', label: 'C2–C7 angle (°) — lordosis positive, kyphosis negative', type: 'number', placeholder: 'e.g. 14 or -6', required: true },
    { id: 'c2c7_sva', label: 'C2–C7 SVA (mm) — optional', type: 'number', placeholder: 'e.g. 18', required: false },
    { id: 't1_slope', label: 'T1 slope (°) — optional', type: 'number', placeholder: 'e.g. 24', required: false },
    { id: 'mcl', label: 'Canal diameter at index level (mm) — optional', type: 'number', placeholder: 'e.g. 10', required: false },
    { id: 'clinical_context', label: 'Clinical context (optional)', type: 'text', placeholder: 'e.g. DCM, cervicogenic pain, post-laminoplasty', required: false },
  ],
  pelvic: [
    { id: 'sex', label: 'Biological sex', type: 'select', options: ['Male', 'Female'], required: true },
    { id: 'age', label: 'Age (years)', type: 'number', placeholder: 'e.g. 61', required: true },
    { id: 'film_type', label: 'Film position', type: 'select', options: ['Standing', 'Supine', 'Prone', 'Unknown'], required: true },
    { id: 'both_heads', label: 'Both femoral heads visible?', type: 'select', options: ['Yes', 'No — midpoint estimated'], required: true },
    { id: 'pi', label: 'Pelvic incidence — PI (°)', type: 'number', placeholder: 'e.g. 52', required: true },
    { id: 'pt', label: 'Pelvic tilt — PT (°)', type: 'number', placeholder: 'e.g. 22', required: true },
    { id: 'ss', label: 'Sacral slope — SS (°)', type: 'number', placeholder: 'e.g. 30', required: true },
    { id: 'clinical_context', label: 'Clinical context (optional)', type: 'text', placeholder: 'e.g. pre-op adult deformity planning, post-fusion follow-up', required: false },
  ],
}

// ─── Validated Clinical Cutoffs (for pre-computation display) ─────────────────
export const CUTOFFS = {
  smi_male_class1: 52.4,
  smi_male_class2: 43.0,
  smi_female_class1: 38.5,
  smi_female_class2: 41.0,
  pmi_male: 6.36,
  pmi_female: 3.84,
  pt_plus: 20,
  pt_plusplus: 30,
  pill_plus: 10,
  pill_plusplus: 20,
  sva_plus: 40,
  sva_plusplus: 95,
}
